spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lifestats
    username: lifestats
    password: lifestats
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/master.xml

server:
  port: 8080